### ISSUE TITLE
Request to transfer my morganey intellij plugin to the organisation

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/organization#2]
Hi All

I am requesting to move my morganey intellij plugin [here](https://github.com/06needhamt/morganey-intellij-plugin) to this organisation as discussed in yesterdays stream so other community members can easily contribute

**Comment by rexim** [comment]
Hi!

Request is accepted! Thanks for joining us! Let's initate the repo transfer.

It's a bit complicated. The repo transfer doesn't work like I thought at the beginning. Only organization admins can transfer their personal repos to the organization directly. So we gonna perform two steps:
1. Please initiate the repo transfer to @rexim in the settings of your repo. Read [GitHub Help](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization) for more information.
2. @rexim will transfer the repo to @morganey-lang

If at any time you want to transfer your repo back, please submit another request here and we will initiate a reversed process. :)

Thanks!

**Comment by 06needhamt** [comment]
That's done

**Comment by rexim** [comment]
Wait you're able to transfer the repo directly to the organization? How did that happen? I didn't even receive any notifications about that... The documentation must be outdated or something.

**Comment by 06needhamt** [comment]
Yes it has all moved over automatically, so is everything good now or what else has to be done?. Also im on stream developing if you would like to watch

**Comment by rexim** [comment]
> Yes it has all moved over automatically, so is everything good now or what else has to be done?

That is it I guess. :) Thanks! Only one last question. Whom did you intiate the repo transfer to? @rexim or @morganey-lang?

> Also im on stream developing if you would like to watch

Oh, I'd like to! But I'm working at the moment. :) I'm gonna watch the recording if it's available. Thanks!

**Comment by 06needhamt** [comment]
It says i don't have push access to the repo

**Comment by rexim** [comment]
> It says i don't have push access to the repo

Please, try now

**Comment by 06needhamt** [comment]
nope my git client gives me this error 
![untitled](https://cloud.githubusercontent.com/assets/4162227/18628525/8490af18-7e58-11e6-9b45-35753a054c71.png)

**Comment by rexim** [comment]
Alright, got it. Give me a second...

**Comment by rexim** [comment]
@06needhamt alright, try now! :)

**Comment by 06needhamt** [comment]
nope

**Comment by rexim** [comment]
This is strange I granted you and your team admin access to the repo... Do you still use your old remote? Maybe that's the problem? Could you please try to change your `origin` remote to `git@github.com:morganey-lang/morganey-intellij-plugin.git`?

**Comment by 06needhamt** [comment]
now i get this error 
![capture](https://cloud.githubusercontent.com/assets/4162227/18628853/21a781cc-7e5a-11e6-8ce2-aa617ad34271.PNG)

**Comment by rexim** [comment]
Alright, let me transfer the repo back and we will figure out what happened.

**Comment by rexim** [comment]
Just to have it captured here. On the stream we saw that it's possible to push via git shell. Looks like a gitkracken's problem. Continue to investigate.

**Comment by 06needhamt** [comment]
Well i sent them an issue hopefully they will get back

**Comment by rexim** [comment]
Alright, please keep us updated. We gonna close the issue once everything's fine.

**Comment by 06needhamt** [comment]
will do

**Comment by 06needhamt** [comment]
Just got the following email back off gitkracken

>  Thank you for using GitKraken!
> 
> Consider your feedback submitted and in review!
> 
> Please note, due to the volume of messages we receive, we cannot respond personally to feedback inquiries on free accounts. 
> 
> Thanks for sharing! 

So in other words we dont read your feedback if you have a free account

**Comment by rexim** [comment]
@06needhamt is everything ok now? Can we close this issue?

**Comment by 06needhamt** [comment]
Yes you can close this issue

**Comment by rexim** [comment]
@06needhamt cool! Thanks for joining us! :)
