### ISSUE TITLE
Label System

### ISSUE THREAD

**Issue by rexim** [morganey-lang/organization#36]
Split from #7 

https://github.com/morganey-lang/morganey-gradle-plugin/pull/10#issuecomment-251694522

**Comment by rexim** [comment]
Duplicate of #21

**Comment by ForNeVeR** [comment]
You should replace the issue link in [DevelopmentProcess](https://github.com/morganey-lang/community/blob/96c1547e73724ec3d755f49d37ab1326795f25e9/DevelopmentProcess.md#label-system) then!

**Comment by rexim** [comment]
@ForNeVeR right! Thank you!
