### ISSUE TITLE
VS Code Extension For Morganey

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/organization#5]
Request to start a repo called 'morganey-vscode-extension' To develop a VS Code extension for the Morganey Language. This project will attempt to implement all of the features in the https://github.com/morganey-lang/morganey-intellij-plugin. Into VS Code

**Comment by rexim** [comment]
@06needhamt are you going to lead that project?

**Comment by 06needhamt** [comment]
I was planning on unless anyone else would like to however my priority will be on the IntelliJ plugin

**Comment by rexim** [comment]
@06needhamt ok. Made you an admin of https://github.com/morganey-lang/morganey-vscode-extension

Feel free to organize the dev process as see needed. :)
