### ISSUE TITLE
Morganey lang Vim plugin

### ISSUE THREAD

**Issue by Newlifer** [morganey-lang/organization#8]
Request to start (or maybe fok [this](https://github.com/Newlifer/morganey.vim)) a repo called 'morganey.vim' to develop a Vim plugin
for the Morganey Language. This project will attempt to implement syntax
coloring and (in planning) running Morganey code right in the glorious Vim.

**Comment by rexim** [comment]
@Newlifer I invited you to the organization. Once you accept the invitation, please transfer https://github.com/Newlifer/morganey.vim to https://github.com/morganey-lang

**Comment by rexim** [comment]
See https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization for more info

**Comment by rexim** [comment]
This is so cool! Thanks for making it! ^_^

![screenshot from 2016-10-04 15-36-59](https://cloud.githubusercontent.com/assets/165283/19069371/d9940272-8a50-11e6-95e7-878d0ace73ab.png)

**Comment by Newlifer** [comment]
Nice!

**Comment by rexim** [comment]
The transfer has been completed! https://github.com/morganey-lang/morganey.vim

**Comment by rexim** [comment]
Welcome to the Morganey Community! :)
